peerProcess: peerProcess.java
	javac peerProcess.java
ResultVerifier: ResultVerifier.java
	javac ResultVerifier.java
clean:
	rm -rf *.class
	rm -rf ./config/*.class
	rm -rf ./connect/*.class
	rm -rf ./connect/message/*.class
	rm -rf ./connect/message/type/*.class
	rm -rf ./connect/piece/*.class
	rm -rf ./main/*.class
	rm -rf ./utils/*.class
