peerProcess: peerProcess.java
	javac peerProcess.java
clean:
	rm -rf *.class
	rm -rf ./config/*.class
	rm -rf ./connect/*.class ./connect/message/*.class ./connect/message/type/*.class ./piece/*.class
	rm -rf ./main/*.class
	rm -rf ./utils/*.class
