version: '3'

services:
  p1:
    image: jdk8:base
    container_name: p1-10.9.0.11
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.11
    command: /bin/bash
  
  p2:
    image: jdk8:base
    container_name: p2-10.9.0.12
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.12
    command: /bin/bash

  p3:
    image: jdk8:base
    container_name: p3-10.9.0.13
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.13
    command: /bin/bash
  
  p4:
    image: jdk8:base
    container_name: p4-10.9.0.14
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.14
    command: /bin/bash

  p5:
    image: jdk8:base
    container_name: p5-10.9.0.15
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.15
    command: /bin/bash
  
  p6:
    image: jdk8:base
    container_name: p6-10.9.0.16
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.16
    command: /bin/bash

networks:
  net-p2p-10.9.0.0:
    name: net-p2p-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24