version: '3'

services:
  p1:
    image: jdk8:base
    container_name: p1-10.9.0.11
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.11
    command: bash -c "cd ./p2p && java peerProcess 1001"
  
  p2:
    image: jdk8:base
    container_name: p2-10.9.0.12
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.12
    command: bash -c "cd ./p2p && java peerProcess 1002"

  p3:
    image: jdk8:base
    container_name: p3-10.9.0.13
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.13
    command: bash -c "cd ./p2p && java peerProcess 1003"
  
  p4:
    image: jdk8:base
    container_name: p4-10.9.0.14
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.14
    command: bash -c "cd ./p2p && java peerProcess 1004"

  p5:
    image: jdk8:base
    container_name: p5-10.9.0.15
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.15
    command: bash -c "cd ./p2p && java peerProcess 1005"
  
  p6:
    image: jdk8:base
    container_name: p6-10.9.0.16
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.16
    command: bash -c "cd ./p2p && java peerProcess 1006"

  p7:
    image: jdk8:base
    container_name: p7-10.9.0.17
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.17
    command: bash -c "cd ./p2p && java peerProcess 1007"

  p8:
    image: jdk8:base
    container_name: p8-10.9.0.18
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.18
    command: bash -c "cd ./p2p && java peerProcess 1008"

  p9:
    image: jdk8:base
    container_name: p9-10.9.0.19
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/p2p:/opt/p2p
    networks:
      net-p2p-10.9.0.0:
        ipv4_address: 10.9.0.19
    command: bash -c "cd ./p2p && java peerProcess 1009"

networks:
  net-p2p-10.9.0.0:
    name: net-p2p-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24