peerProcess: peerProcess.java
	javac peerProcess.java
	javac ResultVerifier.java
clean:
	rm -rf *.class
	rm -rf ./config/*.class
	rm -rf ./main/*.class
	rm -rf ./main/message/*.class
	rm -rf ./main/message/type/*.class
	rm -rf ./main/piece/*.class
	rm -rf ./utils/*.class
	rm -rf ./*.log
